### ISSUE TITLE
x axis label display

### ISSUE THREAD

**Issue by rfcee** [n3-charts/line-chart#327]
Hey all,

I was wondering how to display the x-axis label when there is only  1 value. The plotting of the graph is fine (points along the y axis line), but the x-axis label is not displaying:
![untitled](https://cloud.githubusercontent.com/assets/12604627/9949839/18ba089e-5df6-11e5-9a42-1c45d209a4c6.png)

**Comment by chaosmail** [comment]
Hi @rfcee 
we fixed this in the latest release for x-axis type `date`, for linear scale it should also work fine. here is a demo: http://plnkr.co/edit/0NoimXXs9B6npffC4HSY?p=preview
Otherwise you could manually set `min` and `max` values to fix this.
Best,
Christoph

**Comment by rfcee** [comment]
Hi Christoph,
I modified your plnkr file, but I could still not display the label:

http://plnkr.co/edit/htjEKdlfqFj277hJsaQe?p=preview

How do I display it as the first tick, directly under the y axis?

**Comment by rfcee** [comment]
Ok got it now, I set 
        min:0,
        max: 0.1

for the x axis. thanks again!

**Comment by chaosmail** [comment]
Great, let me know if you have any other problems
